name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Using a common stable version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Build with PyInstaller
      run: |
        pyinstaller --name "FulfillmentCalculator" --onefile --windowed --add-data "src;src" main.py

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/FulfillmentCalculator.exe
        asset_name: FulfillmentCalculator-v${{ github.ref_name }}.exe
        asset_content_type: application/vnd.microsoft.portable-executable
